# -------------------------------
# ANALYTICS SERVICE - BLUE deploy
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-blue
  labels:
    app: analytics-service
    color: blue
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300 #180
  selector:
    matchLabels:
      app: analytics-service
      color: blue
  template:
    metadata:
      labels:
        app: analytics-service
        color: blue
    spec:
      containers:
        - name: analytics-service
          image: avishka20241889/analytics-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12
          livenessProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          startupProbe:
            tcpSocket: { port: 8000 }
            failureThreshold: 30
            periodSeconds: 2
            timeoutSeconds: 2

---
# ---------------------------------
# ANALYTICS SERVICE - GREEN deploy
# ---------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-green
  labels:
    app: analytics-service
    color: green
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300 #180
  selector:
    matchLabels:
      app: analytics-service
      color: green
  template:
    metadata:
      labels:
        app: analytics-service
        color: green
    spec:
      containers:
        - name: analytics-service
          image: avishka20241889/analytics-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          startupProbe:
            tcpSocket: { port: 8000 }
            failureThreshold: 30
            periodSeconds: 2
            timeoutSeconds: 2

---
# ---------------------------------------
# SINGLE SERVICE - points to ONE color
# ---------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics-service
    color: blue         # <--- initial live color (CI will flip this)
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
