# -------------------------------
# ANALYTICS SERVICE - BLUE deploy
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-blue
  labels:
    app: analytics-service
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
      color: blue
  template:
    metadata:
      labels:
        app: analytics-service
        color: blue
    spec:
      containers:
        - name: analytics-service
          image: avishka20241889/analytics-service:latest  # CI will 'set image' to :latest anyway
          ports:
            - containerPort: 8000
          # Use TCP probes so we don't rely on a /health endpoint
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

---
# ---------------------------------
# ANALYTICS SERVICE - GREEN deploy
# ---------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-green
  labels:
    app: analytics-service
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
      color: green
  template:
    metadata:
      labels:
        app: analytics-service
        color: green
    spec:
      containers:
        - name: analytics-service
          image: avishka20241889/analytics-service:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

---
# ---------------------------------------
# SINGLE SERVICE - points to ONE color
# ---------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics-service
    color: blue         # <--- initial live color (CI will flip this)
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
