# -------------------------------
# GAME SERVICE - BLUE deployment
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service-blue
  labels:
    app: game-service
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-service
      color: blue
  template:
    metadata:
      labels:
        app: game-service
        color: blue
    spec:
      containers:
        - name: game-service
          image: avishka20241889/game-service:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1

---
# ---------------------------------
# GAME SERVICE - GREEN deployment
# ---------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service-green
  labels:
    app: game-service
    color: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-service
      color: green
  template:
    metadata:
      labels:
        app: game-service
        color: green
    spec:
      containers:
        - name: game-service
          image: avishka20241889/game-service:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1

---
# ---------------------------------------
# SINGLE SERVICE - points to ONE color
# ---------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  selector:
    app: game-service
    color: blue   # <--- initial live color (flip in CI)
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
