apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      initContainers:
        - name: wait-ch
          image: busybox:1.36
          command: ['sh','-c','until wget -qO- http://clickhouse-server:8123/ping; do echo waiting for clickhouse; sleep 2; done']
      containers:
        - name: analytics-service
          image: cloudcomputingcw-analytics-service:latest
          imagePullPolicy: IfNotPresent
          ports: [{containerPort: 8000}]
          env:
            - name: CLICKHOUSE_HOST
              value: clickhouse-server
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: CLICKHOUSE_DATABASE
              value: analytics
            - name: CLICKHOUSE_TABLE
              value: events
            - name: CLICKHOUSE_USER
              value: default
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-credentials
                  key: password
          readinessProbe:
            httpGet: { path: "/", port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 5


