apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: cloudcomputingcw-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              value: mysql-db
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: clouduser
            - name: MYSQL_PASSWORD
              value: cloudpass
            - name: MYSQL_DB
              value: cloud
