apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  type: NodePort
  ports:
    - port: 8000          # Inside-cluster access
      targetPort: 8000    # Container listens on this port
      nodePort: 30802     # Exposed to localhost:30802
