name: Build & Push Images

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - "game-service/**"
      - "order-service/**"
      - "analytics-service/**"
      - ".github/workflows/build.yml"
  workflow_dispatch:

jobs:
  build:
    # use GitHub's ubuntu runner for clean, fast Docker builds
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - frontend
          - game-service
          - order-service
          - analytics-service

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max