name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours for periodic testing

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/game-service:latest ./game-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/game-service:latest
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest ./order-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/analytics-service:latest ./analytics-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/analytics-service:latest
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Set up kubectl
        run: choco install kubernetes-cli -y

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
